cookbook-db/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.contrib.auth import forms as auth_forms
from django.urls import path, include



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('website.urls'), name='website'),
    path('receptury/', include('recipes.urls'), name='recipes'),
    path('finanse/', include('finance.urls'), name='finance'),
    path('produkty/', include('products.urls'), name='products'),
]



#     #path('login/', auth_views.LoginView(template_name='website/login.html', authentication_form=auth_forms.AuthenticationForm)),

finance/urls.py
from django.contrib import admin
from django.urls import path

from . import views

app_name = 'finance'
urlpatterns = [
    path('', views.finance, name='finance'),
    path('rachunek_zyskow_i_strat', views.new_income_statement, name='new_income_statement'),
]

products/urls.py
from django.urls import path
from . import views

app_name = 'products'
urlpatterns = [
    path('', views.products, name='products'),
    path('<category>', views.products_category, name='products_category'),
]

recipes/urls.py
from django.urls import path

from . import views

app_name = 'recipes'
urlpatterns = [
    path('', views.recipes, name='recipes'),
    path('<category>', views.recipes_cat, name='recipes_cat'),
    path('<category>/<recipe_name>', views.recipes_recipe, name='recipes_recipe'),
]

website/urls.py
from django.urls import path, include
from . import views



app_name = 'website'
urlpatterns = [
    path('', views.login, name='login'),
    path('index', views.index, name='index'),
]

website/models.py
from django.db import models

# Create your models here.

website/views.py
from django.shortcuts import render
from django.contrib import auth
from django.contrib.auth.decorators import login_required

# Create your views here.


def login(request):
    if request.method == 'POST':
        user = auth.authenticate(username=request.POST['username'], password=request.POST['password'])
        if user is not None:
            request.session.set_expiry(86400)
            auth.login(request, user)
            return render(request, 'website/index.html')
        else:
            return render(request, 'website/login_failed.html', {'form': auth.forms.AuthenticationForm})
    else:
        return render(request, 'website/login.html', {'form': auth.forms.AuthenticationForm})


@login_required
def index(request):
    return render(request, 'website/index.html')

website/templates/website/_login_form.html
<div id="login_form">
    <h2> Log in </h2>
    <form method="POST" action="#">
        {% csrf_token %}
        <table>
            {{ form.as_table }}

       </table>
        <button type="submit">Login</button>
    </form>
</div>

website/templates/website/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
{% block head %}
<head>

    <meta charset="UTF-8">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static 'w3style.css' %}">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Lato">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<!--    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">-->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>

</head>
{% endblock %}
<body>


{% block navbar %}
{% endblock %}

{% block sidebar %}
{% endblock %}

{% block content %}
{% endblock %}

{% block javascript %}
{% endblock %}


</body>
</html>

website/templates/website/index.html
{% extends 'website/base.html' %}

<img src="./static/images/jata_logo.png" srcset="./static/images/jata_logo.png 240w" sizes="(max-width: 500px) 200px, 200px" id="logo">
{% block navbar %}
<div class="w3-top">
  <div class="w3-bar w3-black w3-card">
    <a href="{% url 'finance:finance' %}" class="w3-bar-item w3-button w3-padding-large">Finanse</a>
    <a href="{% url 'recipes:recipes' %}" class="w3-bar-item w3-button w3-padding-large">Receptury</a>
    <a href="{% url 'products:products' %}" class="w3-bar-item w3-button w3-padding-large">Produkty</a>
  </div>
</div>
{% endblock %}

website/templates/website/login.html
{% extends 'website/base.html' %}

{% block content %}
{% include 'website/_login_form.html' %}
{% endblock %}

website/templates/website/login2.html
{% extends 'website/base.html' %}
{% block content %}
    <div id="content-container" class="container p-none">
        <div class="lgn-container col-lg-8">
            <form id="login-form" method="post"
                  action="{% url 'auth_login' %}">
                {% csrf_token %}
                <table class="table">
                    <tr>
                        <td><label for="id_username">Username</label></td>
                        <td><input id="id_username" name="username"
                                   type="text" class="form-control"></td>
                    </tr>
                    <tr>
                        <td><label for="id_password">Password</label></td>
                        <td><input id="id_password" name="password"
                                   type="password" class="form-control"></td>
                    </tr>
                </table>
                {% if form.errors %}
                    <p class=" label label-danger">
                        Your username and password didn't match.
                        Please try again.
                    </p>
                {% endif %}

                <input type="submit" value="Login"
                       class="btn btn-primary pull-right" />
                <input type="hidden" name="next" value="{{ next }}" />
            </form>
        </div>
    </div>
{% endblock content %}

website/templates/website/login_failed.html
{% extends 'website/base.html' %}

{% block content %}
{% include 'website/_login_form.html' %}
<p>
    Niepoprawne dane. Spróbuj jeszcze raz.
</p>
{% endblock %}