cookbook-db/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.contrib.auth import forms as auth_forms
from django.urls import path, include



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('website.urls'), name='website'),
    path('receptury/', include('recipes.urls'), name='recipes'),
    path('finanse/', include('finance.urls'), name='finance'),
    path('produkty/', include('products.urls'), name='products'),
]



#     #path('login/', auth_views.LoginView(template_name='website/login.html', authentication_form=auth_forms.AuthenticationForm)),

finance/urls.py
from django.contrib import admin
from django.urls import path

from . import views

app_name = 'finance'
urlpatterns = [
    path('', views.finance, name='finance'),
    path('rachunek_zyskow_i_strat', views.new_income_statement, name='new_income_statement'),
]

products/urls.py
from django.urls import path
from . import views

app_name = 'products'
urlpatterns = [
    path('', views.products, name='products'),
    path('<category>', views.products_category, name='products_category'),
]

website/urls.py
from django.urls import path, include
from . import views



app_name = 'website'
urlpatterns = [
    path('', views.login, name='login'),
    path('index', views.index, name='index'),
]

products/models.py
from django.db import models

# Create your models here.


class ProductCategory(models.Model):
    name = models.CharField(max_length=32, unique=True, blank=False, default='')

    def __str__(self):
        return self.name


class Supplier(models.Model):
    name = models.CharField(max_length=32, unique=True, blank=False)

    def __str__(self):
        return self.name


class Product(models.Model):
    name = models.CharField(max_length=32, unique=True, verbose_name='Produkt')
    category = models.ForeignKey(ProductCategory, null=True, blank=True, on_delete=models.CASCADE,
                                 related_name='product_category', verbose_name='Kategoria')
    unit = models.CharField(max_length=4, choices=[('kg', 'kg'), ('l', 'l'), ('szt', 'szt')], default='kg',
                            verbose_name='Jednostka')
    pack_size = models.FloatField(verbose_name='Rozmiar opakowania')
    pack_price = models.FloatField(verbose_name='Cena opakowania')
    supplier = models.ForeignKey(Supplier, blank=False, related_name='product_supplier', on_delete=models.CASCADE,
                                 verbose_name='Dostawca')

    def __str__(self):
        return f'{self.name} | {self.pack_size} {self.unit} | {self.pack_price} zł | {self.supplier}'

products/forms.py
from django import forms
from .models import ProductCategory, Supplier

class NewSupplier(forms.Form):
    name = forms.CharField(label='Nazwa firmy', max_length=32)


class NewProduct(forms.Form):
    name = forms.CharField(label='Nazwa', max_length=32)
    category = forms.ChoiceField(label='Kategoria')
    unit = forms.ChoiceField(label='Jednostka', choices=[('kg', 'kg'), ('l', 'l'), ('szt', 'szt')])
    pack_size = forms.FloatField(label='Wielkość opakowania')
    pack_price = forms.FloatField(label='Cena opakowania (zł)')
    supplier = forms.ChoiceField(label='Dostawca')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['category'].choices = [(c.id, c.name) for c in ProductCategory.objects.all()]
        self.fields['supplier'].choices = [(c.id, c.name) for c in Supplier.objects.all()]

products/views.py
from django.shortcuts import render
from .models import Product, ProductCategory, Supplier
from django.contrib.auth.decorators import login_required
from .utils import setup_product_categories
from .forms import NewProduct, NewSupplier
# Create your views here.


@login_required
def products(request):
    context = dict()
    context['products'] = Product.objects.all()
    context['suppliers'] = Supplier.objects.all()
    categories = ProductCategory.objects.all()
    context['categories'] = categories
    context['fields'] = ['Produkt', 'Wielkość opakowania', 'Cena opakowania', 'Cena jednostkowa', 'Dostawca']

    if not len(categories):
        setup_product_categories()

    if request.method == 'POST' and 'unit' in str(request.POST):
        form_new_product = NewProduct(request.POST)
        if form_new_product.is_valid():
            form_data = form_new_product.cleaned_data
            new_product = Product.objects.create(name=form_data['name'],
                                                 category=ProductCategory.objects.get(id=form_data['category']),
                                                 unit=form_data['unit'], pack_size=form_data['pack_size'],
                                                 pack_price=form_data['pack_price'],
                                                 supplier=Supplier.objects.get(id=form_data['supplier']))
            new_product.save()
        else:
            print(form_new_product.errors)

    elif request.method == 'POST' and 'name' in str(request.POST):
        form_new_supplier = NewSupplier(request.POST)
        if form_new_supplier.is_valid():
            form_data = form_new_supplier.cleaned_data
            new_supplier = Supplier.objects.create(**form_data)
            new_supplier.save()
            print('saved supp')

    elif request.method == 'POST' and request.is_ajax:
        ids = request.POST['checked_ids'].split(',')
        for prod_id in ids:
            Product.objects.get(id=int(prod_id)).delete()

    context['form_new_product'] = NewProduct()
    context['form_new_supplier'] = NewSupplier()
    return render(request, 'products/products.html', context=context)


@login_required
def products_category(request, category):
    context = dict()
    context['products'] = Product.objects.filter(category=ProductCategory.objects.get(name=category))
    context['suppliers'] = Supplier.objects.all()
    categories = ProductCategory.objects.all()
    context['categories'] = categories
    context['fields'] = ['Produkt', 'Wielkość opakowania', 'Cena opakowania', 'Cena jednostkowa', 'Dostawca']

    if not len(categories):
        setup_product_categories()

    if request.method == 'POST' and 'unit' in str(request.POST):
        form_new_product = NewProduct(request.POST)
        if form_new_product.is_valid():
            form_data = form_new_product.cleaned_data
            new_product = Product.objects.create(name=form_data['name'],
                                                 category=ProductCategory.objects.get(id=form_data['category']),
                                                 unit=form_data['unit'], pack_size=form_data['pack_size'],
                                                 pack_price=form_data['pack_price'],
                                                 supplier=Supplier.objects.get(id=form_data['supplier']))
            new_product.save()
        else:
            print(form_new_product.errors)

    elif request.method == 'POST' and 'name' in str(request.POST):
        form_new_supplier = NewSupplier(request.POST)
        if form_new_supplier.is_valid():
            form_data = form_new_supplier.cleaned_data
            new_supplier = Supplier.objects.create(**form_data)
            new_supplier.save()

    elif request.method == 'POST' and request.is_ajax:
        ids = request.POST['checked_ids'].split(',')
        for prod_id in ids:
            Product.objects.get(id=int(prod_id)).delete()

    context['form_new_product'] = NewProduct()
    context['form_new_supplier'] = NewSupplier()

    return render(request, 'products/products.html', context)

products/templates/products/_product_table.html
<table id="product_table" border="1" cellpadding="5">
    <thead>
        <tr>
            {% for header in fields %}
            <th>
                {{ header }}
            </th>
            {% endfor %}
        </tr>
    </thead>

    {% if products %}
    {% for product in products %}
    <tr>
        <td>{{ product.name }}</td>
        <td>{{ product.pack_size }}</td>
        <td>{{ product.pack_price }} zł</td>
        <td>{% widthratio product.pack_price product.pack_size 1 %} zł</td>
        <td>{{ product.supplier }}</td>
        <td>
            <input type="checkbox" id="{{ product.id }}">
        </td>
    </tr>
    {% endfor %}
    {% endif %}
</table>

products/templates/products/products.html
{% extends 'website/base.html' %}
{% load static %}

{% block navbar %}
    <div class="w3-bar w3-black w3-card">
        <a href="{% url 'website:index' %}" class="w3-bar-item w3-button w3-padding-large"> Home </a>
        <a href="/produkty" class="w3-bar-item w3-button w3-padding-large"> Wszystkie produkty </a>
        {% for category in categories %}
        <a href="{% url 'products:products_category' category %}" class="w3-bar-item w3-button w3-padding-large">{{ category.name }}</a>
        {% endfor %}
    </div>
{% endblock %}

{% block sidebar %}
    <div id="products">
        <div id="products_top">
            <h3><b> Produkty </b></h3>
            <h4 id="products_filter"> Filtr: </h4>
            <input type="text" id="products_filter_text"/>
            <form id="del_from_db" method="POST" action="#">
                {% csrf_token %}
                <input type="hidden" name="checked_ids" value="" id="js_data_input"/>
                <button type="submit" onclick="updateChecked()" name="submit" value="Submit" id="del_from_db2"> Usuń </button>
            </form>
        </div>
        {% include 'products/_product_table.html' %}
    </div>
{% endblock %}

{% block content %}
    <div id="new_product">
        <form method="post" action="#">
        {% csrf_token %}
            <table cellpadding="8">
                <thead>
                    <tr>
                        <th colspan="2">
                            <h3><b> Dodaj produkt </b></h3>
                        </th>
                    </tr>
                </thead>
                <tbody>
                    {{ form_new_product }}
                </tbody>
            </table>
        <button id="save_product" type="submit" value="save"> Zapisz </button>
        </form>
    </div>

    <div id="new_supplier">
        <form method="post" action="#">
        {% csrf_token %}
            <table>
                <thead>
                    <tr>
                        <th colspan="2">
                            <h3><b> Nowy dostawca </b></h3>
                        </th>
                    </tr>
                </thead>
                <tbody>
                    {{ form_new_supplier }}
                </tbody>
            </table>
            <button id="save_supplier" type="submit" value="save"> Zapisz </button>
        </form>
    </div>

    <div id="supplier_list">
        <h3><b> Dostawcy </b></h3>
        <ul id="supplier_ul">
        {% for supplier in suppliers %}
            <li> {{ supplier }} </li>
        {% endfor %}
        </ul>
    </div>

{% endblock %}

{% block javascript %}
<script src="{% static 'findChecked.js' %}" type="text/javascript"></script>
<script src="{% static 'filterProducts.js' %}" type="text/javascript"></script>
{% endblock %}