cookbook-db/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.contrib.auth import forms as auth_forms
from django.urls import path, include



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('website.urls'), name='website'),
    path('receptury/', include('recipes.urls'), name='recipes'),
    path('finanse/', include('finance.urls'), name='finance'),
    path('produkty/', include('products.urls'), name='products'),
]



#     #path('login/', auth_views.LoginView(template_name='website/login.html', authentication_form=auth_forms.AuthenticationForm)),

finance/urls.py
from django.contrib import admin
from django.urls import path

from . import views

app_name = 'finance'
urlpatterns = [
    path('', views.finance, name='finance'),
    path('rachunek_zyskow_i_strat', views.new_income_statement, name='new_income_statement'),
]

website/urls.py
from django.urls import path, include
from . import views



app_name = 'website'
urlpatterns = [
    path('', views.login, name='login'),
    path('index', views.index, name='index'),
]

finance/models.py
from django.db import models


# Create your models here.


class IncomeStatement(models.Model):
    date = models.DateField(verbose_name='Data', null=True, unique=True, blank=False)
    sales = models.FloatField(blank=False, null=True, verbose_name='Sprzedaż razem')
    n_of_sales = models.IntegerField(blank=True, null=True, verbose_name='Liczba paragonów')

    rent = models.FloatField(blank=True, null=True, verbose_name='Czynsz')
    water = models.FloatField(blank=True, null=True, verbose_name='Woda')
    gas = models.FloatField(blank=True, null=True, verbose_name='Gaz')
    electricity = models.FloatField(blank=True, null=True, verbose_name='Prąd')
    garbage = models.FloatField(blank=True, null=True, verbose_name='Śmieci')
    net_phone = models.FloatField(blank=True, null=True, verbose_name='Internet/telefon')
    security = models.FloatField(blank=True, null=True, verbose_name='Ochrona')
    accounting_hr = models.FloatField(blank=True, null=True, verbose_name='Księgowość/kadry')
    marketing = models.FloatField(blank=True, null=True, verbose_name='Marketing/reklama')
    terminal_fee = models.FloatField(blank=True, null=True, verbose_name='Prowizja terminal')
    chemicals = models.FloatField(blank=True, null=True, verbose_name='Chemia')
    equipment = models.FloatField(blank=True, null=True, verbose_name='Wyposażenie restauracji')
    repairs = models.FloatField(blank=True, null=True, verbose_name='Naprawy/serwisy')
    license_fees = models.FloatField(blank=True, null=True, verbose_name='Opłaty, pozwolenia, koncesje')
    training = models.FloatField(blank=True, null=True, verbose_name='Badania/szkolenia')
    dress = models.FloatField(blank=True, null=True, verbose_name='Stroje służbowe')
    fuel = models.FloatField(blank=True, null=True, verbose_name='Paliwo')
    office_equipment = models.FloatField(blank=True, null=True, verbose_name='Materiały biurowe')
    laundry = models.FloatField(blank=True, null=True, verbose_name='Pralnia/sprzątanie')

    kitchen = models.FloatField(blank=True, null=True, verbose_name='Koszt surowca kuchnia')
    bar = models.FloatField(blank=True, null=True, verbose_name='Koszt surowca bar')
    events = models.FloatField(blank=True, null=True, verbose_name='Koszt surowca bankiety/eventy')
    employee_meals = models.FloatField(blank=True, null=True, verbose_name='Koszt surowca posiłki pracownicze')
    snacks = models.FloatField(blank=True, null=True, verbose_name='Koszt surowca poczęstunki')

    kitchen_eom_stock = models.FloatField(blank=True, null=True, verbose_name='Stan magazynu na koniec miesiąca: kuchnia')
    bar_eom_stock = models.FloatField(blank=True, null=True, verbose_name='Stan magazynu na koniec miesiąca: bar')

    salaries = models.FloatField(blank=True, null=True, verbose_name='Wynagrodzenia netto')
    zus = models.FloatField(blank=True, null=True, verbose_name='ZUS')
    tax = models.FloatField(blank=True, null=True, verbose_name='Podatek')
    bonuses = models.FloatField(blank=True, null=True, verbose_name='Premie/prowizje')
    other = models.FloatField(blank=True, null=True, verbose_name='Inne koszty personelu')

    n_of_working_days = models.IntegerField(blank=True, null=True, verbose_name='Liczba dni roboczych w miesiącu')
    n_of_workhours = models.IntegerField(blank=True, null=True, verbose_name='Liczba godzin przepracowanych')

finance/forms.py
from django import forms
from .models import IncomeStatement

from cookbookdb import settings

input_formats=settings.DATE_INPUT_FORMATS


class AddIncomeStatement(forms.Form):
    sales = forms.FloatField(label='Sprzedaż razem', required=False, max_value=100000000)
    n_of_sales = forms.IntegerField(label='Liczba paragonów', required=False, max_value=100000000)

    rent = forms.FloatField(label='Czynsz', required=False, max_value=10000000)
    water = forms.FloatField(label='Woda', required=False, max_value=100000000)
    gas = forms.FloatField(label='Gaz', required=False, max_value=100000000)
    electricity = forms.FloatField(label='Prąd', required=False, max_value=100000000)
    garbage = forms.FloatField(label='Śmieci', required=False, max_value=100000000)
    net_phone = forms.FloatField(label='Internet/telefon', required=False, max_value=100000000)
    security = forms.FloatField(label='Ochrona', required=False, max_value=100000000)
    accounting_hr = forms.FloatField(label='Księgowość/kadry', required=False, max_value=100000000)
    marketing = forms.FloatField(label='Marketing/reklama', required=False, max_value=100000000)
    terminal_fee = forms.FloatField(label='Prowizja terminal', required=False, max_value=100000000)
    chemicals = forms.FloatField(label='Chemia', required=False, max_value=100000000)
    equipment = forms.FloatField(label='Wyposażenie restauracji', required=False, max_value=100000000)
    repairs = forms.FloatField(label='Naprawy/serwisy', required=False, max_value=100000000)
    license_fees = forms.FloatField(label='Opłaty, pozwolenia, koncesje', required=False, max_value=100000000)
    training = forms.FloatField(label='Badania/ szkolenia', required=False, max_value=100000000)
    dress = forms.FloatField(label='Stroje służbowe', required=False, max_value=100000000)
    fuel = forms.FloatField(label='Paliwo', required=False, max_value=100000000)
    office_equipment = forms.FloatField(label='Materiały biurowe', required=False, max_value=100000000)
    laundry = forms.FloatField(label='Pralnia/sprzątanie', required=False, max_value=100000000)

    kitchen = forms.FloatField(label='Koszt surowca kuchnia', max_value=100000000)
    bar = forms.FloatField(label='Koszt surowca bar', max_value=100000000)
    events = forms.FloatField(label='Koszt surowca bankiety/eventy', max_value=100000000)
    employee_meals = forms.FloatField(label='Koszt surowca posiłki pracownicze', max_value=100000000)
    snacks = forms.FloatField(label='Koszt surowca poczęstunki', max_value=100000000)

    kitchen_eom_stock = forms.FloatField(label='Stan magazynu na koniec miesiąca: kuchnia', max_value=100000000)
    bar_eom_stock = forms.FloatField(label='Stan magazynu na koniec miesiąca: bar', max_value=100000000)

    salaries = forms.FloatField(label='Wynagrodzenia netto', max_value=100000000)
    zus = forms.FloatField(label='ZUS', max_value=100000000)
    tax = forms.FloatField(label='Podatek', max_value=100000000)
    bonuses = forms.FloatField(label='Premie/prowizje', max_value=100000000)
    other = forms.FloatField(label='Inne koszty personelu', max_value=100000000)

    n_of_working_days = forms.IntegerField(label='Liczba dni roboczych w miesiącu', max_value=31)
    n_of_workhours = forms.IntegerField(label='Liczba godzin przepracowanych', max_value=100000)

finance/views.py
from django.shortcuts import render, HttpResponse, HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from django.urls import reverse
from django.core import serializers
from .forms import AddIncomeStatement
from .models import IncomeStatement
from .utils import TABLE_INDEX, calculate_financials, calculate_aggregate_costs, get_sorted_statement
import datetime

# Create your views here.


@login_required
def finance(request):
    data = []
    financial_statements = IncomeStatement.objects.values()

    for statement in financial_statements:
        financials, costs = calculate_financials(statement)
        sorted_statement = get_sorted_statement(statement, costs, financials)
        data.append(sorted_statement)

    return render(request, 'finance/finance.html', context={'data': data, 'fields': TABLE_INDEX})


@login_required
def new_income_statement(request):
    if request.method == 'POST':
        data = AddIncomeStatement(request.POST)
        if data.is_valid():
            statement = data.cleaned_data
            statement['date'] = datetime.date(year=int(request.POST['date_input'].split('-')[0]),
                                          month=int(request.POST['date_input'].split('-')[1]),
                                              day=30)
            obj = IncomeStatement.objects.create(**statement)
            obj.save()
        else:
            print(data.errors)
        return HttpResponseRedirect(reverse('finance:finance'))
    else:
        form = AddIncomeStatement()
        return render(request, 'finance/new_income_statement.html', context={'form': form})

finance/templates/finance/_pnl_table.html
<table id="pnl_table" border="=1" cellpadding="4">
    <thead>

    </thead>
    <tbody>
        <tr>
            {% for field in fields %}
            <td>
                {{ field }}
            </td>
            {% endfor %}
        </tr>

        {% for statement in data %}
        <tr>
            {% for value in statement.0 %}
                <td>
                    {{ value }}
                </td>
            {% endfor %}
        </tr>
        <tr>
            {% for value in statement.1 %}
                {% if value %}
                    <td>
                        {{ value }}%
                    </td>
                {% else %}
                    <td>
                    </td>
                {% endif %}
            {% endfor %}
        </tr>
        {% endfor %}

    </tbody>
</table>

finance/templates/finance/finance.html
{% extends 'website/base.html' %}
{% load static %}


{% block navbar %}
    <div class="w3-bar w3-black w3-card">
        <a href="{% url 'website:index' %}" class="w3-bar-item w3-button w3-padding-large"> Home </a>
        <a href="{% url 'finance:finance' %}" class="w3-bar-item w3-button w3-padding-large"> Sprawozdania</a>
        <a href="{% url 'finance:new_income_statement' %}" class="w3-bar-item w3-button w3-padding-large">Dodaj sprawozdanie</a>
    </div>
{% endblock %}

{% block sidebar %}
{% endblock %}

{% block content %}
{% include 'finance/_pnl_table.html' %}
{% endblock %}


{% block javascript %}
<script src="{% static 'transpose.js' %}" type="text/javascript">
</script>
<script src="{% static 'formatRows.js' %}" type="text/javascript">
</script>
{% endblock %}

finance/templates/finance/new_income_statement.html
{% extends 'finance/finance.html' %}
{% load static %}


{% block content %}
<div id="pnl_statement">
    <h3 id="new_statement_title"><b> Rachunek zysków i strat </b></h3>
    <form id="pnl_statement_form" method="post" action="#">
        {% csrf_token %}
            <table cellpadding="3">
                <thead>
                    <th>
                        <label for="date_input"> Data: </label>
                    </th>
                    <th>
                        <input type="month" id="date_input" name="date_input">
                    </th>
                </thead>
            {{ form }}
            </table>
        <button id="save_statement" type="submit" value="save"> Zapisz </button>
    </form>
</div>
{% endblock %}


{% block javascript %}
<script type="text/javascript">
    let today = new Date();
    let dateWidget = document.getElementById('date_input');
    dateWidget.valueAsDate = today;
</script>
{% endblock %}